# SonarQube Project Configuration
sonar.projectKey=greenfund-backend
sonar.projectName=GreenFund Backend
sonar.projectVersion=1.0.0

# Source code
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Encoding
sonar.sourceEncoding=UTF-8

# JaCoCo Coverage
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.exclusions=**/model/dto/**,**/config/**,**/exception/**,**/model/entity/**,**/model/enums/**

# Exclusions
sonar.exclusions=**/model/dto/**,**/config/**,**/exception/**,**/model/entity/**,**/model/enums/**

# Test exclusions
sonar.test.exclusions=**/*Test.java

# Language
sonar.language=java

